// Generated by gencpp from file voice_msgs/aiui_server.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_AIUI_SERVER_H
#define VOICE_MSGS_MESSAGE_AIUI_SERVER_H

#include <ros/service_traits.h>


#include <voice_msgs/aiui_serverRequest.h>
#include <voice_msgs/aiui_serverResponse.h>


namespace voice_msgs
{

struct aiui_server
{

typedef aiui_serverRequest Request;
typedef aiui_serverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct aiui_server
} // namespace voice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voice_msgs::aiui_server > {
  static const char* value()
  {
    return "18b580cf575766ccf649862f1dd31583";
  }

  static const char* value(const ::voice_msgs::aiui_server&) { return value(); }
};

template<>
struct DataType< ::voice_msgs::aiui_server > {
  static const char* value()
  {
    return "voice_msgs/aiui_server";
  }

  static const char* value(const ::voice_msgs::aiui_server&) { return value(); }
};


// service_traits::MD5Sum< ::voice_msgs::aiui_serverRequest> should match 
// service_traits::MD5Sum< ::voice_msgs::aiui_server > 
template<>
struct MD5Sum< ::voice_msgs::aiui_serverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::aiui_server >::value();
  }
  static const char* value(const ::voice_msgs::aiui_serverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::aiui_serverRequest> should match 
// service_traits::DataType< ::voice_msgs::aiui_server > 
template<>
struct DataType< ::voice_msgs::aiui_serverRequest>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::aiui_server >::value();
  }
  static const char* value(const ::voice_msgs::aiui_serverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voice_msgs::aiui_serverResponse> should match 
// service_traits::MD5Sum< ::voice_msgs::aiui_server > 
template<>
struct MD5Sum< ::voice_msgs::aiui_serverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::aiui_server >::value();
  }
  static const char* value(const ::voice_msgs::aiui_serverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::aiui_serverResponse> should match 
// service_traits::DataType< ::voice_msgs::aiui_server > 
template<>
struct DataType< ::voice_msgs::aiui_serverResponse>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::aiui_server >::value();
  }
  static const char* value(const ::voice_msgs::aiui_serverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_AIUI_SERVER_H
