// Generated by gencpp from file voice_msgs/aiui_serverResponse.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_AIUI_SERVERRESPONSE_H
#define VOICE_MSGS_MESSAGE_AIUI_SERVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_msgs
{
template <class ContainerAllocator>
struct aiui_serverResponse_
{
  typedef aiui_serverResponse_<ContainerAllocator> Type;

  aiui_serverResponse_()
    : iat_str()
    , nlp_str()  {
    }
  aiui_serverResponse_(const ContainerAllocator& _alloc)
    : iat_str(_alloc)
    , nlp_str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _iat_str_type;
  _iat_str_type iat_str;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nlp_str_type;
  _nlp_str_type nlp_str;





  typedef boost::shared_ptr< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct aiui_serverResponse_

typedef ::voice_msgs::aiui_serverResponse_<std::allocator<void> > aiui_serverResponse;

typedef boost::shared_ptr< ::voice_msgs::aiui_serverResponse > aiui_serverResponsePtr;
typedef boost::shared_ptr< ::voice_msgs::aiui_serverResponse const> aiui_serverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_msgs::aiui_serverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f760ae5fc192d3e3607111fe07ee4e3a";
  }

  static const char* value(const ::voice_msgs::aiui_serverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf760ae5fc192d3e3ULL;
  static const uint64_t static_value2 = 0x607111fe07ee4e3aULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_msgs/aiui_serverResponse";
  }

  static const char* value(const ::voice_msgs::aiui_serverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string iat_str\n\
string nlp_str\n\
\n\
\n\
";
  }

  static const char* value(const ::voice_msgs::aiui_serverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.iat_str);
      stream.next(m.nlp_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aiui_serverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_msgs::aiui_serverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_msgs::aiui_serverResponse_<ContainerAllocator>& v)
  {
    s << indent << "iat_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.iat_str);
    s << indent << "nlp_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nlp_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_AIUI_SERVERRESPONSE_H
