// Generated by gencpp from file voice_msgs/collect.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_COLLECT_H
#define VOICE_MSGS_MESSAGE_COLLECT_H

#include <ros/service_traits.h>


#include <voice_msgs/collectRequest.h>
#include <voice_msgs/collectResponse.h>


namespace voice_msgs
{

struct collect
{

typedef collectRequest Request;
typedef collectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct collect
} // namespace voice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voice_msgs::collect > {
  static const char* value()
  {
    return "23d6fc1b3d3189aa83b1d24eb3e0750b";
  }

  static const char* value(const ::voice_msgs::collect&) { return value(); }
};

template<>
struct DataType< ::voice_msgs::collect > {
  static const char* value()
  {
    return "voice_msgs/collect";
  }

  static const char* value(const ::voice_msgs::collect&) { return value(); }
};


// service_traits::MD5Sum< ::voice_msgs::collectRequest> should match 
// service_traits::MD5Sum< ::voice_msgs::collect > 
template<>
struct MD5Sum< ::voice_msgs::collectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::collect >::value();
  }
  static const char* value(const ::voice_msgs::collectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::collectRequest> should match 
// service_traits::DataType< ::voice_msgs::collect > 
template<>
struct DataType< ::voice_msgs::collectRequest>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::collect >::value();
  }
  static const char* value(const ::voice_msgs::collectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voice_msgs::collectResponse> should match 
// service_traits::MD5Sum< ::voice_msgs::collect > 
template<>
struct MD5Sum< ::voice_msgs::collectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::collect >::value();
  }
  static const char* value(const ::voice_msgs::collectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::collectResponse> should match 
// service_traits::DataType< ::voice_msgs::collect > 
template<>
struct DataType< ::voice_msgs::collectResponse>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::collect >::value();
  }
  static const char* value(const ::voice_msgs::collectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_COLLECT_H
