// Generated by gencpp from file voice_msgs/collectResponse.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_COLLECTRESPONSE_H
#define VOICE_MSGS_MESSAGE_COLLECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_msgs
{
template <class ContainerAllocator>
struct collectResponse_
{
  typedef collectResponse_<ContainerAllocator> Type;

  collectResponse_()
    : ret()  {
    }
  collectResponse_(const ContainerAllocator& _alloc)
    : ret(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::voice_msgs::collectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_msgs::collectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct collectResponse_

typedef ::voice_msgs::collectResponse_<std::allocator<void> > collectResponse;

typedef boost::shared_ptr< ::voice_msgs::collectResponse > collectResponsePtr;
typedef boost::shared_ptr< ::voice_msgs::collectResponse const> collectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_msgs::collectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_msgs::collectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::collectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::collectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::collectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::collectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::collectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::collectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_msgs::collectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7030931189f40243cd08ed0e4c0bac7";
  }

  static const char* value(const ::voice_msgs::collectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7030931189f4024ULL;
  static const uint64_t static_value2 = 0x3cd08ed0e4c0bac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_msgs::collectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_msgs/collectResponse";
  }

  static const char* value(const ::voice_msgs::collectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_msgs::collectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ret\n\
\n\
";
  }

  static const char* value(const ::voice_msgs::collectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_msgs::collectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_msgs::collectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_msgs::collectResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_COLLECTRESPONSE_H
