// Generated by gencpp from file voice_msgs/collectRequest.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_COLLECTREQUEST_H
#define VOICE_MSGS_MESSAGE_COLLECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_msgs
{
template <class ContainerAllocator>
struct collectRequest_
{
  typedef collectRequest_<ContainerAllocator> Type;

  collectRequest_()
    : collect_flag(0)  {
    }
  collectRequest_(const ContainerAllocator& _alloc)
    : collect_flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _collect_flag_type;
  _collect_flag_type collect_flag;





  typedef boost::shared_ptr< ::voice_msgs::collectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_msgs::collectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct collectRequest_

typedef ::voice_msgs::collectRequest_<std::allocator<void> > collectRequest;

typedef boost::shared_ptr< ::voice_msgs::collectRequest > collectRequestPtr;
typedef boost::shared_ptr< ::voice_msgs::collectRequest const> collectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_msgs::collectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_msgs::collectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::collectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::collectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::collectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::collectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::collectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::collectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_msgs::collectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e495bc3e9f444e0d702decea3e8225f4";
  }

  static const char* value(const ::voice_msgs::collectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe495bc3e9f444e0dULL;
  static const uint64_t static_value2 = 0x702decea3e8225f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_msgs::collectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_msgs/collectRequest";
  }

  static const char* value(const ::voice_msgs::collectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_msgs::collectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 collect_flag\n\
";
  }

  static const char* value(const ::voice_msgs::collectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_msgs::collectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collect_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_msgs::collectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_msgs::collectRequest_<ContainerAllocator>& v)
  {
    s << indent << "collect_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.collect_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_COLLECTREQUEST_H
