// Generated by gencpp from file voice_msgs/ss_server.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_SS_SERVER_H
#define VOICE_MSGS_MESSAGE_SS_SERVER_H

#include <ros/service_traits.h>


#include <voice_msgs/ss_serverRequest.h>
#include <voice_msgs/ss_serverResponse.h>


namespace voice_msgs
{

struct ss_server
{

typedef ss_serverRequest Request;
typedef ss_serverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ss_server
} // namespace voice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voice_msgs::ss_server > {
  static const char* value()
  {
    return "7aeed7b72cdf8a5bf3a4d5fe07dde8a0";
  }

  static const char* value(const ::voice_msgs::ss_server&) { return value(); }
};

template<>
struct DataType< ::voice_msgs::ss_server > {
  static const char* value()
  {
    return "voice_msgs/ss_server";
  }

  static const char* value(const ::voice_msgs::ss_server&) { return value(); }
};


// service_traits::MD5Sum< ::voice_msgs::ss_serverRequest> should match 
// service_traits::MD5Sum< ::voice_msgs::ss_server > 
template<>
struct MD5Sum< ::voice_msgs::ss_serverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::ss_server >::value();
  }
  static const char* value(const ::voice_msgs::ss_serverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::ss_serverRequest> should match 
// service_traits::DataType< ::voice_msgs::ss_server > 
template<>
struct DataType< ::voice_msgs::ss_serverRequest>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::ss_server >::value();
  }
  static const char* value(const ::voice_msgs::ss_serverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voice_msgs::ss_serverResponse> should match 
// service_traits::MD5Sum< ::voice_msgs::ss_server > 
template<>
struct MD5Sum< ::voice_msgs::ss_serverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voice_msgs::ss_server >::value();
  }
  static const char* value(const ::voice_msgs::ss_serverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_msgs::ss_serverResponse> should match 
// service_traits::DataType< ::voice_msgs::ss_server > 
template<>
struct DataType< ::voice_msgs::ss_serverResponse>
{
  static const char* value()
  {
    return DataType< ::voice_msgs::ss_server >::value();
  }
  static const char* value(const ::voice_msgs::ss_serverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_SS_SERVER_H
