// Generated by gencpp from file voice_msgs/ss_serverResponse.msg
// DO NOT EDIT!


#ifndef VOICE_MSGS_MESSAGE_SS_SERVERRESPONSE_H
#define VOICE_MSGS_MESSAGE_SS_SERVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_msgs
{
template <class ContainerAllocator>
struct ss_serverResponse_
{
  typedef ss_serverResponse_<ContainerAllocator> Type;

  ss_serverResponse_()
    : voice_file()  {
    }
  ss_serverResponse_(const ContainerAllocator& _alloc)
    : voice_file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _voice_file_type;
  _voice_file_type voice_file;





  typedef boost::shared_ptr< ::voice_msgs::ss_serverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_msgs::ss_serverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ss_serverResponse_

typedef ::voice_msgs::ss_serverResponse_<std::allocator<void> > ss_serverResponse;

typedef boost::shared_ptr< ::voice_msgs::ss_serverResponse > ss_serverResponsePtr;
typedef boost::shared_ptr< ::voice_msgs::ss_serverResponse const> ss_serverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_msgs::ss_serverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_msgs::ss_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_msgs::ss_serverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_msgs::ss_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c8c41dcd20ae51d3de95db4bcaee566";
  }

  static const char* value(const ::voice_msgs::ss_serverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c8c41dcd20ae51dULL;
  static const uint64_t static_value2 = 0x3de95db4bcaee566ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_msgs/ss_serverResponse";
  }

  static const char* value(const ::voice_msgs::ss_serverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string voice_file\n\
\n\
";
  }

  static const char* value(const ::voice_msgs::ss_serverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ss_serverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_msgs::ss_serverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_msgs::ss_serverResponse_<ContainerAllocator>& v)
  {
    s << indent << "voice_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.voice_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_MSGS_MESSAGE_SS_SERVERRESPONSE_H
